"$schema" = 'https://starship.rs/config-schema.json'

right_format = """
    [î‚²](cyan)\
    $cmd_duration\
    [î‚²](bg:cyan fg:purple)\
    $c\
    $golang\
    $java\
    $nodejs\
    $rust\
    [î‚²]( bg:purple fg:green)\
    $kubernetes\
    $terraform\
    $pulumi\
    [î‚²](bg:green fg:red)\
    $status\
    [î‚´](red)\
"""

format = """
[î‚¶](purple)\
    $os\
    $username\
    [î‚°](bg:orange fg:purple)\
    $directory\
    [î‚°](fg:orange bg:yellow)\
    $git_branch\
    $git_status\
    [î‚°](fg:yellow bg:blue)\
    $gcloud\
    $azure\
    $aws\
[î‚°](fg:blue)\
"""

# Disable the blank line at the start of the prompt
add_newline = true

palette = 'inherenc'

[palettes.inherenc]
blue = '#4285f4'
green = '#06969A'
orange = '#DA627D'
yellow = '#FCA17D'
cyan = '#86BBD8'
purple = '#9A348E'

[aws]
    format = '[$symbol ($profile)(\($region\) )]($style)'
    style = 'bold bg:#4285f4 fg:white'
    # symbol = ' ğŸ…° '
    symbol = " â˜ï¸"
    # [aws.region_aliases]
    # us-east-1 = 'va'

[azure]
    disabled = true
    format = '[ $symbol($subscription) ]($style)'
    symbol = 'ï´ƒ '
    style = 'bg:blue fg:white bold'


[gcloud]
    format = '[ $symbol$account | $active]($style)'
    symbol = "î² " #"â˜ï¸ " # "â˜ï¸ "
    style = 'bold bg:blue fg:white'

[pulumi]
    disabled = false
    format = '[| $symbol($username@)$stack ]($style)'
    style = 'bg:blue fg:white bold'

[terraform]
    format = '[$symbol$workspace(\($version\))]($style)'
    style = 'bold bg:green'

# You can also replace your username with a neat symbol like ï„   or disable this
# and use the os module below
[username]
    show_always = true
    style_user = "bg:purple fg:white"
    style_root = "bg:purple"
    format = '[$user]($style)'
    disabled = true

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
    style = "bg:purple fg:white bold"
    disabled = false # Disabled by default

[os.symbols]
    # Macos = "ï£¿ "
    Macos = "\ue711 "

[directory]
    style = "bg:orange fg:white"
    format = "[$path]($style)"
    truncation_length = 3
    truncation_symbol = "â€¦/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
    "Documents" = "ïœ˜ "
    "Downloads" = "ï€™ "
    "Music" = "ï€ "
    "Pictures" = "ï€¾ "
    # Keep in mind that the order matters. For example:
    # "Important Documents" = " ïœ˜ï„ª "
    # will not be replaced, because "Documents" was already substituted before.
    # So either put "Important Documents" before "Documents" or use the substituted version:
    # "Important ïœ˜ " = " ïœ˜ï„ª "

[docker_context]
    symbol = "ïŒˆ "
    style = "bg:green fg:white"
    format = '[ $symbol$context ]($style)$path'

[kubernetes]
    format = '[$symbol$context( \($namespace\)) ]($style)'
    disabled = false
    style = "bg:green fg:white"
    # detect_folders = [ "_kustomize" ]

[git_branch]
    symbol = "ï˜"
    style = "bg:yellow"
    format = '[ $symbol $branch]($style)'

[git_status]
    style = "bg:yellow"
    modified = "!$count "
    stashed = '*$count '
    ahead = 'â‡¡${count} '
    diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count} '
    behind = 'â‡£${count} '
    format = '[ $all_status$ahead_behind]($style)'

[c]
    symbol = "î˜ "
    style = "bg:purple fg:white"
    format = '[ $symbol ($version) ]($style)'

[golang]
    symbol = "î˜§ "
    style = "bg:purple fg:white"
    format = '[ $symbol ($version) ]($style)'

[java]
    symbol = "î‰– "
    style = "bg:purple fg:white bold"
    format = '[ $symbol($version) ]($style)'

[nodejs]
    symbol = "îœ˜"
    style = "bg:purple fg:white"
    format = '[( $symbol $version )]($style)'

[rust]
    symbol = "î¨"
    style = "bg:purple fg:white"
    format = '[ $symbol ($version) ]($style)'

[status]
    style = 'bg:red fg:white'
    symbol = 'âœ˜ '
    success_symbol = 'âœ” '
    format = '[($symbol$common_meaning$signal_name$maybe_int)]($style)'
    map_symbol = true
    disabled = false

[cmd_duration]
    min_time = 500
    style = "bg:cyan"
    format = '[ $duration ï‰’ ]($style)'

[time]
    disabled = false
    time_format = "%R" # Hour:Minute Format
    # style = "bg:#33658A"
    style = "bg:green fg:white"
    format = '[ â™¥ $time ]($style)'
